### ISSUE TITLE
Build does not proceed, waits for ever 

### ISSUE THREAD

**Issue by ht512512** [openshift/nodejs-ex#124]
OS: Ubuntu 16.04
Installed 'oc' and did oc cluster up
Connected to the Web Console
In my-project, created an app ("an-app") using 'https://github.com/openshift/nodejs-ex.git' (actually just clicked try-it button that fills this in).
It started build 1 that did not do anything (just the spinning icon). Canceled after 40 min. Tried again. Same fate for build 2.

Builds
an-app                      Build #2 is pending              created 4 minutes ago
                                  Build #1 was cancelled        created an hour ago

Not sure if any other config is required!

**Comment by bparees** [comment]
all your builds remain in "pending"?

Can you run an "oc describe" on the build pod and the build and report the results?

"oc get pods -o yaml" would also be helpful.

**Comment by ht512512** [comment]
oc describe builds
==============
- Seems to not like the docker version string !!
==============
Name:		an-app-1
Namespace:	my-project
Created:	About a minute ago
Labels:		app=an-app
		buildconfig=an-app
		openshift.io/build-config.name=an-app
		openshift.io/build.start-policy=Serial
Annotations:	openshift.io/build-config.name=an-app
		openshift.io/build.number=1
		openshift.io/build.pod-name=an-app-1-build

Status:		Pending
Duration:	waiting for 1m29s
Build Config:	an-app
Build Pod:	an-app-1-build

Strategy:	Source
URL:		https://github.com/openshift/nodejs-ex.git
Ref:		master
From Image:	DockerImage centos/nodejs-4-centos7@sha256:a166ee3d5cfd04c6a08f758f35bce9d4fc6cf6b2387d15b2998be6a36ccea63a
Output to:	ImageStreamTag an-app:latest
Push Secret:	builder-dockercfg-q63gh

Build trigger cause:	Build configuration change

Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  1m		1m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned an-app-1-build to localhost
  1m		8s		7	{kubelet localhost}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.1-ce\": illegal zero-prefixed version component \"03\" in \"17.03.1-ce\""

**Comment by bparees** [comment]
paging @csrwng

**Comment by bparees** [comment]
(fyi this is really an openshift/origin issue, not a nodejs example issue, so next time consider opening the issue there)

**Comment by ht512512** [comment]
Thanks.

**Comment by csrwng** [comment]
@ht512512 if you are using cluster up to start your cluster, try with --version=v1.5.0  
The other alternative is to downgrade your docker to v1.13.1

**Comment by ht512512** [comment]
@csrwng Thanks. With --version=v1.5.0 the build fails with unable to clone the app. Seems like origin is not able to network out (Could not resolve host error in the log)

**Comment by ht512512** [comment]
In monitoring, I see an event with the following error, " kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy. "

**Comment by csrwng** [comment]
@ht512512 do you by any chance a firewall running?

**Comment by csrwng** [comment]
It sounds like this is an issue with pod networking and not necessarily the nodejs example.
Please open in origin if things are not working right after running cluster up (or contact me directly for help)
