### ISSUE TITLE
cannot pull images from docker registry

### ISSUE THREAD

**Issue by suiwenfeng** [openshift/nodejs-ex#129]
W0629 20:26:40.909717   16192 dockerimagelookup.go:220] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: http: error connecting to proxy
https://127.0.0.1:8087: dial tcp 127.0.0.1:8087: getsockopt: connection refused
error: no tags found on matching image stream: "openshift/nodejs"

The image stream "openshift/nodejs" exists, but it has no tags.

  Use --allow-missing-imagestream-tags to use this image stream

**Comment by bparees** [comment]
This is an issue with your openshift cluster, not the sample app, please open an issue against origin and we'll try to help you there.
