### ISSUE TITLE
How to use an image nodejs: 8?

### ISSUE THREAD

**Issue by vs0uz4** [openshift/nodejs-ex#144]
In RedHat Container Catalog there is the image:
>registry.access.redhat.com/rhscl-beta/nodejs-8-rhel7

how can I use it in the repository example?

**Comment by bparees** [comment]
easiest way:
`oc new-app registry.access.redhat.com/rhscl-beta/nodejs-8-rhel7~https://github.com/openshift/nodejs-ex`
