### ISSUE TITLE
Application crashes if MongoDB is down/removed

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/nodejs-ex#17]
I'd expect the application to keep running and reconnect to the database when it is back up.
It should serve pages just like the example template with no database.

```
[vagrant@openshiftdev origin]$ oc scale rc mongodb-1 --replicas=0
[vagrant@openshiftdev origin]$ oc logs -f nodejs-frontend-1-f7rsm
npm info it worked if it ends with ok
npm info using npm@1.3.24
npm info using node@v0.10.25
npm info prestart nodejs-ex@0.0.1
npm info start nodejs-ex@0.0.1

> nodejs-ex@0.0.1 start /opt/openshift/src
> node server.js

Server running on 0.0.0.0:8080

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

npm info nodejs-ex@0.0.1 Failed to exec start script
npm ERR! nodejs-ex@0.0.1 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the nodejs-ex@0.0.1 start script.
npm ERR! This is most likely a problem with the nodejs-ex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejs-ex
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.17.4-301.fc21.x86_64
npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "start" "-d"
npm ERR! cwd /opt/openshift/src
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.17.4-301.fc21.x86_64
npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "start" "-d"
npm ERR! cwd /opt/openshift/src
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/openshift/src/npm-debug.log
npm ERR! not ok code 0
[vagrant@openshiftdev origin]$ oc get pod
NAME                      READY     REASON       RESTARTS   AGE
nodejs-example-1-build    0/1       ExitCode:0   0          1h
nodejs-frontend-1-f7rsm   0/1       Running      11         1h
```

**Comment by mfojtik** [comment]
@rhcarvalho restarting the container till the database is ready is actually OK, I can see another error in your log:

```
npm ERR! stack Error: EACCES, open 'npm-debug.log'
```

This seems like nodejs is unable to store the debug logs when it crashes... It should not store it but dump into stdout.

**Comment by rhcarvalho** [comment]
@mfojtik I don't think it is OK. It means your application is down when it shouldn't, for no good reason.

Imagine you start from the template with no database (initial state): open your browser and see the welcome page. Then plug in MongoDB, go to your browser, refresh the page, and see database connection info. Remove the database, refresh the page and suddenly the service is gone, you see nothing but your browser's error page.

I'd expect the application to be back to its initial state, instead of having the frontend service down.

**Comment by mfojtik** [comment]
@rhcarvalho I thought that container restart will put the application into initial state.

**Comment by mfojtik** [comment]
@rhcarvalho meaning that if the database is unplugged for some reasonable amount of time, then the app should timeout and container should restart... when a new container start and won't see mongodb it should show you the initial state.

**Comment by rhcarvalho** [comment]
Currently it keeps restarting, never goes back to initial state -- see `oc get pod` above with 11 restarts.

**Comment by PI-Victor** [comment]
i'll fix this in an upcoming PR.
@bparees  can you asign this to me?

**Comment by bparees** [comment]
@PI-Victor i can't because you don't seem to be a member of this repo.  @danmcp can you add @PI-Victor to all the -ex repos so i can assign issues to him?

**Comment by PI-Victor** [comment]
@danmcp @bparees can we create an openshift-devex team for github and place all of us under that since we pretty much maintain these repos?

**Comment by danmcp** [comment]
>  @danmcp can you add @PI-Victor to all the -ex repos so i can assign issues to him?

@bparees Done.

**Comment by rhcarvalho** [comment]
@PI-Victor did you have chance to look at this lately?

**Comment by PI-Victor** [comment]
@rhcarvalho yes, i was writing something with promises but not sure how that will work out on older versions of node. i'm still looking into it

**Comment by PI-Victor** [comment]
are we ok with closing this, since @bparees  fixed this in https://github.com/openshift/nodejs-ex/pull/52 ?

**Comment by bparees** [comment]
i'm not sure it's totally fixed.  if the DB is down, i believe the app still becomes unresponsive until the DB comes back, rather than serving pages that say "no db available".

we need some sort of a timeout on the db requests, which we don't currently have.

**Comment by mfojtik** [comment]
can we add readiness check for the app container that exercise the db
connection?

-- 
Michal Fojtik

**Comment by bparees** [comment]
@mfojtik that doesn't help with the scenario in question here, where the db goes away *after* the app is up.

**Comment by bparees** [comment]
well, i guess it sort of does, it would make the app unavailable again.  but that's not what we want.  we want soft-fail.  the app should still serve the welcome page, just w/o the pagecount.

**Comment by rhcarvalho** [comment]
The way I promote the use of readiness probes, they should normally not rely on dependent services.
Doing so in a distributed system would lead to a cascade of services taken out of operation, instead of graceful degradation.

**Comment by bparees** [comment]
I think that depends on what "dependent" means.  There certainly are going to be cases where you do not want your pod to serve traffic if it cannot reach the DB (this just doesn't happen to be one of those cases).

Consider the case where you have 3 pods and only one of them can't reach the DB for some reason.  Does it make more sense to serve a degraded experience to 1/3 of your users, or to take that pod out of readiness entirely and serve a good experience to everyone using the remaining 2 pods?

**Comment by mfojtik** [comment]
@bparees yeah, to me "ready" means the app is ready (and healthy) to serve traffic to users. If the app requires database to do so, then the readiness check should exercise that (and liveness probe should follow). If the db connection drop from the single pod for some reason, the container should be restarted asap?

**Comment by bparees** [comment]
requests now hang while the DB is down, but if the DB comes back up, it recovers.  I'm considering that "good enough" since it's not worth us investing in this sample app to make it more robust to connection timeouts.
