### ISSUE TITLE
Using a fully qualified route name is inflexible

### ISSUE THREAD

**Issue by smarterclayton** [openshift/nodejs-ex#21]
https://github.com/openshift/nodejs-ex/blob/master/openshift/templates/nodejs.json#L207 hardcodes a default name that will never resolve.  Let's not do that.

**Comment by sspeiche** [comment]
This is just a default for the parameter value, so it can be changed whenever some does new-app. Should we not give a default? When we were developing the sample apps, we found it was handy to have the routes created and giving the parameter a sensible default to start (best we could come up with) based on plan for future routes https://github.com/openshift/rails-ex/issues/9#issuecomment-112433580

**Comment by smarterclayton** [comment]
All you should need is the name of the route (which you have to have anyway).  The problem with this route is it doesn't work (and won't work for anyone).  Probably better to default host to empty and document you can set a host name.

**Comment by bparees** [comment]
https://github.com/openshift/nodejs-ex/blob/master/openshift/templates/nodejs.json#L45
now defaults to "":
https://github.com/openshift/nodejs-ex/blob/master/openshift/templates/nodejs.json#L265
