### ISSUE TITLE
Produces a 404 for path-based routing but works for host-based routing

### ISSUE THREAD

**Issue by whitlockjc** [openshift/nodejs-ex#31]
When I deploy this application to Origin, if I use `host` based routing, the application runs fine.  Here is an example Origin route definition that works:

```yaml
apiVersion: v1
kind: Route
metadata:
  name: nodejs-ex
  namespace: test
  selfLink: /oapi/v1/namespaces/test/routes/nodejs-ex
  uid: aba40cb4-c6ba-11e5-8245-525400659b2e
  resourceVersion: '3418'
  creationTimestamp: '2016-01-29T19:01:15Z'
  labels:
    app: nodejs-ex
spec:
  host: nodejs-ex.origin.local
  to:
    kind: Service
    name: nodejs-ex
  port:
    targetPort: 8080
status: {  }
```

But if I do `path` based routing, it fails.  Here is an example Origin route definition that does not work:

```yaml
apiVersion: v1
kind: Route
metadata:
  name: nodejs-ex
  namespace: test
  selfLink: /oapi/v1/namespaces/test/routes/nodejs-ex
  uid: 65190bae-c6bb-11e5-8245-525400659b2e
  resourceVersion: '3511'
  creationTimestamp: '2016-01-29T19:06:26Z'
  labels:
    app: nodejs-ex
spec:
  host: origin.local
  path: /nodejs-ex
  to:
    kind: Service
    name: nodejs-ex
  port:
    targetPort: 8080
status: {  }
```

There are no errors printed to the pod logs and the only pertinent error I see in the browser is the `Cannot GET /nodejs-ex`  _(or 404)_ from Express.  I realize this is likely due to the [Express mountpath](http://expressjs.com/en/api.html#app.mountpath) needing to be set.  *(If that is the case, it would be great if this could be configurable via an environment variable so you can throw the setting in your pod definition.)*

In all honesty, I would had expected a client request to `/nodejs-ex` to be seen as a request to `/` at the container/pod level but that's more of an Origin issue...or an expectation issue.

Feel free to punt on this.  I just figured that since I ran into it I would report it.  For local development, I like doing `path` based routing so that I only have to update `/etc/hosts` once and that's how I ran into this.

**Comment by bparees** [comment]
closing in deference to the origin issue which is the right place to track this.
