### ISSUE TITLE
MongoDB config

### ISSUE THREAD

**Issue by brennv** [openshift/nodejs-ex#41]
I'm likely missing something, but after following the README, my index page reads "Page view count: No database configured". Should there be an additional step that takes advantage of template/nodejs-mongodb.json?

This was my hacky work-around:

`oc new-app centos/mongodb-26-centos7 -e MONGODB_USER=admin,MONGODB_DATABASE=mongo_db,MONGODB_PASSWORD=secret,MONGODB_ADMIN_PASSWORD=super-secret`

Followed by:

`oc new-app https://github.com/openshift/nodejs-ex -l name=myapp -e MONGO_URL=mongodb://admin:secret@172.30.201.71:27017/mongo_db`

**Comment by bparees** [comment]
yeah, we should have some additional doc that either suggests the steps you figured out on your own (nice work!) to add a DB manually, or points people to the template which will set everything up for them.

**Comment by brennv** [comment]
Cool, I updated my fork of the readme with the steps I took if it helps. https://github.com/brennv/nodejs-ex

**Comment by sspeiche** [comment]
@brennv Please submit PR with changes so we can merge in here

**Comment by PI-Victor** [comment]
you can also use new-app with openshift/template/nodejs.json or nodejs-mongodb.json example. but that's not exactly mentioned anywhere in the README.

**Comment by brennv** [comment]
@sspieche PR submitted.  
@PI-Victor I agree. Demo template processing instructions would be very helpful -- I'd be happy to add it, but I'm unclear on how to utilize the template files. Reading the docs [here](https://docs.openshift.org/latest/dev_guide/templates.html#generating-a-list-of-objects). Would that look something like:

`oc process -f <filename> | oc create -f -`

**Comment by PI-Victor** [comment]
@brennv sorry for not being specific! yes, after you clone this repo `oc new-app -f /path/to/nodejs-mongodb.json` it will take care of the rest for you. good job on the PR!

**Comment by brennv** [comment]
@PI-Victor Thank you! I understand now -- I missed the forest for the trees. :) I'll work it into the PR now.

**Comment by brennv** [comment]
Added instructions on building from templates. Cleaned-up the outline to demonstrate the flexibility of `oc new-app`. Thanks all -- very cool stuff. https://github.com/openshift/nodejs-ex/pull/40/files

**Comment by brennv** [comment]
https://github.com/openshift/nodejs-ex/pull/44
