### ISSUE TITLE
failed to build after push

### ISSUE THREAD

**Issue by sunorth** [openshift/nodejs-ex#53]
I0704 01:27:38.482414       1 builder.go:57] Master version "v3.2.1.3-1-gcbaf600", Builder version "v3.2.1.3-1-gcbaf600"
I0704 01:27:38.486774       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:536870912, CPUShares:61, CPUPeriod:100000, CPUQuota:100000, MemorySwap:536870912}
I0704 01:27:38.492152       1 sti.go:206] The value of ALLOWED_UIDS is [1-]
I0704 01:27:38.492177       1 sti.go:214] The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
I0704 01:27:38.496811       1 docker.go:355] Using locally available image "registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest"
I0704 01:27:38.499234       1 sti.go:233] Creating a new S2I builder with build config: "Builder Name:\t\t\tNode.js 0.10\nBuilder Image:\t\t\tregistry.access.redhat.com/openshift3/nodejs-010-rhel7:latest\nSource:\t\t\t\tfile:///tmp/s2i-build879299895/upload/src#679224040c80fd1c8cb821fd1176b185ccfd4875\nOutput Image Tag:\t\tsunorth/node-sunorth-6:0f85c344\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=node-sunorth-6,OPENSHIFT_BUILD_NAMESPACE=sunorth,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/nodejs-ex.git,OPENSHIFT_BUILD_REFERENCE=master,OPENSHIFT_BUILD_COMMIT=679224040c80fd1c8cb821fd1176b185ccfd4875\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build879299895\nDocker NetworkMode:\t\tcontainer:1c4e05efb479587443098cb37b02d1558c13a0bfb64cef10937290b5099ff44f\nDocker Endpoint:\t\tunix:///var/run/docker.sock\n"
I0704 01:27:38.501772       1 docker.go:355] Using locally available image "registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest"
I0704 01:27:38.510749       1 docker.go:355] Using locally available image "registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest"
I0704 01:27:38.510778       1 docker.go:475] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0704 01:27:38.510819       1 sti.go:140] Preparing to build sunorth/node-sunorth-6:0f85c344
I0704 01:27:38.514347       1 source.go:197] Downloading "https://github.com/openshift/nodejs-ex.git" ...
I0704 01:27:38.813728       1 source.go:208] Cloning source from https://github.com/openshift/nodejs-ex.git
I0704 01:27:39.138032       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build879299895
I0704 01:27:39.138075       1 fs.go:156] Removing directory '/tmp/s2i-build879299895'
F0704 01:27:39.139964       1 builder.go:204] Error: build error: fatal: reference is not a tree: 679224040c80fd1c8cb821fd1176b185ccfd4875

**Comment by bparees** [comment]
can you provide the steps you used to get to this point, and also the buildconfig json definition?

it appears you have a buildconfig that's referencing a non-existent git commit: 6792240

**Comment by bparees** [comment]
Are you triggering this build via a github webhook that is defined on your own fork of this repo?  If so, you also need to update your buildconfiguration to be building your fork of the repo, not the openshift fork.

**Comment by sunorth** [comment]
thanks, it works
