### ISSUE TITLE
the route is not accepting traffic yet because it has not been admitted by a router

### ISSUE THREAD

**Issue by zhouhuakang** [openshift/nodejs-ex#58]
Backgroud:
1.I have seen the video[1],and try it on my Ubuntu 14,it seems that build successfully
Problems:
1.But after i want to visit the URL,it shows that i can not visit it,the in the "Browse->Routes",i find that there is waring showing "the route is not accepting traffic yet because it has not been admitted by a router"
2.Why?How can i fix it?Becasue I use the Ubuntu?

[1][https://access.redhat.com/videos/1606273](https://access.redhat.com/videos/1606273)

**Comment by bparees** [comment]
This sounds like an issue w/ your cluster configuration, not the nodejs example.  Please open an issue against github.com/openshift/origin and we'll see if someone can help sort out your configuration problem there.
