### ISSUE TITLE
Test are not able against remote instance

### ISSUE THREAD

**Issue by tnozicka** [openshift/nodejs-ex#59]
[Test](https://github.com/openshift/nodejs-ex/blob/master/tests/app_test.js) are not able to run against remote instance and always try to listen on specified (local) IP.

Setting environment variable IP to remote address does not work because tests are always trying to listen on this IP because they include [server](https://github.com/openshift/nodejs-ex/blob/master/tests/app_test.js#L1) and [it always try to listen on that ip](https://github.com/openshift/nodejs-ex/blob/master/server.js#L104).

@PI-Victor Could you please modify them so they are able to connect to remote instance?

**Comment by bparees** [comment]
The purpose of that test is to be running inside the resulting image for local testing of the post-commit hook.  What are you trying to use it for?

**Comment by tnozicka** [comment]
@bparees We would like to use them as an example of integration tests. We would deploy the app to OpenShift cluster and run these tests against the (remote) instance. 

I would guess it will be quite easy to put this option there.

**Comment by tnozicka** [comment]
(This is meant as an additional option to current functionality, not to replace it.)

**Comment by bparees** [comment]
you're welcome to submit a PR and tag me.

**Comment by tnozicka** [comment]
@bparees Unfortunately I don't know Node.js at all :( I actually talked to @PI-Victor in person yesterday and asked him if he could do this change if it's ok? I might learn it, but it seemed like a much faster solution as he was the one who wrote those tests.

**Comment by PI-Victor** [comment]
@bparees i'll give @tnozicka a hand and submit a PR in the upcoming days, for what i looked in the tests libraries it should be a simple env var to add and point to the URL to tests.
