### ISSUE TITLE
Build fails behind proxy

### ISSUE THREAD

**Issue by stobias123** [openshift/nodejs-ex#68]
I'm running OS 1.3 and this build fails behind a authenticated proxy due to an "unescaped character". 

Proxy works fine with all other examples. What's wrong here?

```
npm ERR! Request path contains unescaped characters.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
```

**Comment by coreydaley** [comment]
Can you provide any addition details about your configuration such as:
Any proxy configuration information: Are you using some configuration in an .npmrc file? Or is it configured at the Operating System or Network level?
Dependencies for your project being installed by npm: your package.json file? (in a public gist)
Independent testing: Can you install the dependencies on another machine behind the same proxy?

Answers to these questions will aid us in helping to diagnose your issue.

**Comment by bparees** [comment]
Are you using the RHEL or centos image?  Are you on the latest one? There
was a problem with one of the older nodejs packages that caused this but
it.shpuld be fixed in the latest images... Definitely centos. Not sure if
the RHEL image has been updated with the fix yet.

If you're having issues on the latest centos image, can you give exact
recreate steps?

Ben Parees | OpenShift

**Comment by stobias123** [comment]
@coreydaley The proxy is set globally in openshift. There is zero configuration of the project as far as npmrc or package.json. I just pasted this git repo into openshift.

@bparees I'm using centos image, just deleted and re-imported the node image stream so it's the most recent. Steps are just to select the nodejs4 template, put in the example project git. 

The proxy has an exclamation mark in it. All other characters are URL encoded. I think this might be the issue, but it's not causing problems anywhere else. Is there somewhere I can set the NPM proxy specifically for just this app?

**Comment by bparees** [comment]
@stobias123 this is the logic that sets up the npm proxy:
https://github.com/sclorg/s2i-nodejs-container/blob/master/4/s2i/bin/assemble#L25-L43

so if npm doesn't like "!" then that's something we'd need to take upstream to npm to address...  are you able to use that proxy value when using npm manually (outside our nodejs image)?

also it sounds like we should move this discussion to the nodejs repository (github.com/sclorg/s2i-nodejs-container), can you reopen this issue there?
