### ISSUE TITLE
Template fails to deploy to OpenShift

### ISSUE THREAD

**Issue by Shogan** [openshift/nodejs-ex#69]
Hi,

I have an app deployed on the OpenShift (3.x?) platform for the Devpost Hackathon projects, and the other day my MongoDB pod seemed to enter a failed state. I scaled it down, then back up again to 1, as I would normally do to sort out issues with connectivity, and it didn't come up that time - just hangs on a yellow status of "Pending".

Upon looking at logs, it looks like it times out waiting for a Persistent Volume claim.

I thought I would completely blow away the project and create one fresh from this nodejs-ex template as I did originally to start with, and to my surprise, the template fails too.

It seems like it can't attach the storage when the mongodb pod is created.

Looking at the yaml for the template, it looks like it tries to mount it to /var/lib/mongodb/data but fails.

This is what I get in my events:

5:24:03 PM	Warning	Failed mount 	Unable to mount volumes for pod "mongodb-2-mal06_myprojectname(d1e4d766-8ed2-11e6-8c36-1242bf1820d9)": Could not attach EBS Disk "aws://us-east-1c/vol-c4540017": Timeout waiting for volume state
30 times in the last 6 hours
5:24:03 PM	Warning	Failed sync 	Error syncing pod, skipping: Could not attach EBS Disk "aws://us-east-1c/vol-c4540017": Timeout waiting for volume state
30 times in the last 

(I cannot see any logs as the container doesn't even manage to start. Querying for logs with the oc cli fails).

**Comment by bparees** [comment]
This sounds like an openshift issue, not a nodejs example issue, can you please open this there(github.com/openshift/origin) so we can get the right people involved?

Thanks

**Comment by sspeiche** [comment]
@Shogan you can also checkout the Google Groups and other ways to get help at https://openshift.devpost.com/details/resources for the hackathon, it sounds like you issue might be related to an operational tool that helps manage PVs
